import type { Metadata } from "next";
import "./globals.css";
import { ThemeProvider } from "@/lib/providers/next-theme-provider";
import { Inter } from '@next/font/google';

export const metadata: Metadata = {
  title: "Brainstorm",
  description: "Generated by create next app",
};

const inter = Inter({ subsets: ['latin'], variable: '--font-inter' });

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}
      >
        <ThemeProvider attribute="class" enableSystem defaultTheme="dark">{children}</ThemeProvider>
      </body>
    </html>
  );
}
