import type { Metadata } from "next";
import "./globals.css";
import { ThemeProvider } from "@/lib/providers/next-theme-provider";

export const metadata: Metadata = {
  title: "Brainstorm",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
      >
        <ThemeProvider attribute="class" enableSystem defaultTheme="dark">{children}</ThemeProvider>
      </body>
    </html>
  );
}
