import type { Metadata } from "next";
import "./globals.css";
import { ThemeProvider } from "@/lib/providers/next-theme-provider";
import db from "@/lib/supabase/db";
import { DM_Sans } from "@next/font/google";
import { twMerge } from "tailwind-merge";
import { Toaster } from "@/components/ui/toaster";

export const metadata: Metadata = {
  title: "Brainstorm",
  description: "Generated by create next app",
};

const dmSans = DM_Sans({subsets:['latin']});

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={twMerge('bg-background',dmSans.className)}
      >
        <ThemeProvider attribute="class" enableSystem defaultTheme="dark">
          <Toaster/>
          {children}
          </ThemeProvider>
      </body>
    </html>
  );
}
